[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'base64-sol/=node_modules/base64-sol/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'hardhat/=node_modules/hardhat/',
    'lil-nouns/=lib/lilnouns-monorepo/packages/nouns-contracts/contracts/',
    'lilnouns-monorepo/=lib/lilnouns-monorepo/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
]
libraries = []
cache = true
cache_path = 'cache'
broadcast = 'broadcast'
allow_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 10_000
verbosity = 0
ignored_error_codes = [
    1878,
    5574,
]
fuzz_runs = 256
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = []
extra_output_files = ['abi', 'metadata']
fuzz_max_local_rejects = 1024
fuzz_max_global_rejects = 65536
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = 'ipfs'
sparse_mode = false
build_info = false

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'

[profile.production]
optimizer_runs = 10_000
extra_output = []
extra_output_files = ['abi']
